### ISSUE TITLE
Proposal incubator

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#92]
From #91:

> Random idea: "proposal incubator" - people can get feedback on their talks and ideas before the review process. That could help to nurture a new audience who isn't sure if they fit in.

**Comment by rkdarst** [comment]
Thinking more about this, submitting to a review system (indico) locks everything away until it becomes the main schedule.  This is good if you are afraid to let anyone see your stuff until it's public (or you are a competitive scientist who has to protect all your work from the public until you can get credit), but make the "getting advance review" part harder, since you have to maintain a separate copy.  While submitting my JupyterCon proposal, I thought how easy it would be if I could share my submission entry directly in the review system before the deadline, and have people comment there.  But, then it's not a blind review.

An incubator could be "submit proposal to a github repo, we will comment there".  It will also provide more opportunity for merging and finding co-authors (only if our community is active enough).  It's not that much a stretch to use the advance comments as part of the reviews, or even reviewing directly by the github issue tracker. Really, we could make a more continuous process, at least late submissions can be considered for a last-minute ad-hoc track.

Fully public submissions and reviews, however, means that there is more fear of submitting something you aren't sure about.  Maybe that is compensated for by seeing what other people have submitted?  Also, requiring a github account is a bit much.  And does an issue tracker provide the high-level management tools we need?

**Comment by bast** [comment]
I am only wondering whether this repo is the right place to collect proposals. But maybe it is since the program is in this repo, too.

**Comment by rkdarst** [comment]
Yeah, this repo isn't really the right place.  But it seemed like an incubator wasn't coming, so I special-cased my proposal and put it here. (in general, I would make another repo under nordic-rse for proposals and possibly also as a way to distribute the content).  Someone else can decide...

**Comment by bast** [comment]
OK I will make a new repo and move your proposal in there.

**Comment by bast** [comment]
What is a good name for a repo? `conference-proposals`? `event-proposals`? `proposal-incubator`?

**Comment by rkdarst** [comment]
What about "2020-meetup" or "2020-online" (whatever our public slug
is) and then it's reusable beyond proposals, to accepted talks,
program, etc?

**Comment by bast** [comment]
OK working on it ...

**Comment by wleoncio** [comment]
Looks good, but if you wanna keep things a bit more generic, I'd suggest renaming the repo "meetups", then issues like https://github.com/nordic-rse/2020-meetup/issues/1 could be labeled "proposal" with something like "2020-online-meetup" as milestone. I've been using milestones a lot lately, after discovering it can have deadlines and it tracks the % of closed issues linked to it.

**Comment by bast** [comment]
Good idea. Renamed.

**Comment by bast** [comment]
Should we add more text somewhere about the incubator? Or can we close this one?

**Comment by wleoncio** [comment]
Some descriptive text is always nice, but I say we close this one for now; if someone thinks of some text to put in they can just edit the file themselves.
