### ISSUE TITLE
5 submission categories may be a barrier for types that are not listed

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#96]
From #95 

> Not saying that something needs to be done now, but this would seem to increase the barrier for other types of events such as more panels, discussions, etc. (they only fit into "mini-workshop". I'm not sure what to do, since the types listed make it much easier to plan and schedule...

This relates to this text at https://nordic-rse.org/conference/submissions/:

> We welcome any type of proposal for this conference but our forms will be structured
for five categories (see below).

**Comment by rkdarst** [comment]
Also for posters, I would like to expand beyond traditional posters (which I always saw as a lot of effort to make, and not much use to read).  In our yearly CS research day, they give options for a poster stand (place to hang paper), or TV screen to show a demo.  It may be hard to find a lot of TV screens, but if they have them it would be nice... worst case, places to host laptops to demonstrate.  (of course then they can't be left there unlocked while unattended... so there has to actually be a session.)

**Comment by rkdarst** [comment]
This is a bit too much of a stretch so I don't expect it to be accepted, but consider the idea that "everything we already need to know already exists".  We could propose good youtube talks to be watched together, along with in-person host(s).  We can pause and discuss, discuss in the hackmd, debate afterwards, etc.  This would feel bad because "why do we have to do this this in-person", but it's not that far from "why do we have to come together to talk to each other awayway?"...

**Comment by bast** [comment]
Yes! I also always found the preparation/impact ration of a poster really disappointing. We did it because there was nothing else but why not offer more options? Indeed.

**Comment by rkdarst** [comment]
To expand, there's an intersection of formats and types:
- {static display, lightning, short, workshop, plenary}
- × {talk, discussion, panel, media display, ...}
... but it's a bit too late.

**Comment by bast** [comment]
Hopefully this is now "solved"?
